name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea7a213e6a6c236f389be8dbbf84a7e440c320dc86a794e9bcd40022b937a77a"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
