name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b056404ebae258dc7ec9fb5a4353e7c1577fd4cdf42f5e2e46beae288610950b"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
