name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc8a1d9685706af5367818fbe3185a4771d8b9148fabea6f3cb6f1d70acf0519"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
