name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2d710b6c4d62b2c9fb9ffd8ef8c5e8a184d5a5c02627cc1158ec5e96fb8e0bf"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
