name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62965f6668c4cbfe6904117994a0daf36262349f5056f7724f6c0b5b0f85aca9"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
