name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "321c23c05211a1f7c57fb75d9c273bc82e555a6f7d09b2b7715e064a0fa6119a"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
