name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.8.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4788a4689c370c6000cbf3b193ba9b811d35ce297ed7b75892ad069bfc2db2ad"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
