name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "770721e75c4546a23d2fbcf84a787f1ddfd692b4d7849a9fc1a544116a17b2ad"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
