name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e50151660e66e7ece50eaa21544a0a6163b4dc706a353efa539c3ae584c37187"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
