name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.6.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25aba00ab8c419747a09cfb192bb6f5e2caa98983efd2439f20055e1d23726ba"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
