name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.6.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b8f4d1876c43926c048ac918246ea211801dac6117904c817afec3778eb5186"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
