name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.8.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65548c306bec5999240ce704764513a71cc1ed5054b4eb454fd71e713699a7c7"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
