name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24b5a3c1552b22ad2fa7892e25089cdd7e593bf80041f3b0743f8a5f68810d5c"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
