name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b365f813ecee22278ef010965a5d30397aca8ff76f91ba72a63c80e4770a4ead"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
