name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7c37aec308843109b8a176629f466f16a63fbe3a028b54637c097de51225bd8"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
