name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.6.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c6966f7a20069495a6a3e8dbccfaafa72219da5ab8cb0ae7b27910a2c1bd9d8"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
