name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.6.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "449e211661f37d75ed96ee83c97963b8d1e1ec76eef28d4b681611c30f319ba2"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
