name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7d4aa956234153c4d1790a58cce995cd7dfe84ceed8fa036c29c1045ce2d5b0"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
