name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.6.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b00fe20a92b965ecd48d51ca8bf2571443191ed9ee791eb265fd765b8342e126"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
