name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bcecf4a566d72c6134de4f2c6c9a8e65ae91f596121ee481c26aff3486f270d"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
