name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4205f2d37e7bfe2c32f5b232f38dd80e95a923a687f40f76bf9930c9e7e58b98"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
