name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d7c26a5280b8c8b72f026a9100f61491d76c334780e25e7c9bf99484ad45903"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
