name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.6.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc6d1727cc33be09cb750d181e9eeeb274ff1f550c2e8ec8f650366eca78ff8a"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
