name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af3d2739f127c6be1d82c357bc363ced697227082cf3b7c4a275841e98c71f79"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
