name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca42a3637fe49607c080e6ae130a6f12a202f62fe95868c065cea5978d4fd268"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
