name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52788b044427691e7e90e8afaa67d14034d4464f002b7e18b25f384f21516fbb"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
