name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90ed5c989d167dfd9478fb10d48ce0e2fd58a5649436a4ec3d2e84242c2fc6a0"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
